### PR TITLE
feat: allow manufacturer to be specified

### LINKED ISSUE #72: Add option to set manufacture
See cyclone DX reference: https://cyclonedx.org/docs/1.5/json/#metadata_manufacture_contact
There shall be manufacture (v1.5) manufacturer (v1.6) field about the organization.
Is it planned to inject such metadata during BOM generation?

### PR DESCRIPTION
**Pull request by jeremylong**
resolves #72

### CODE REVIEW

**Comment by jeremylong** [comment]
Is it really necessary to avoid having 6 parameters? If it is, I can refactor. but there will be a number of changes.

**Review by macblazer — APPROVED** [review]

**Comment by macblazer** [comment]
And, of course, the unit tests must pass before this can be merged.

**Comment by jeremylong** [comment]
Thanks - will fix the unit tests. They passed locally, so I'll try and figure out what is happening.

**Comment by jeremylong** [comment]
I think I fixed everything in this one - however, it looks like codacy didn't run. This is honestly the first ruby code I've written...

**Review by macblazer — APPROVED** [review]

**Review by macblazer — APPROVED** [review]

**Pull request merged**
